name: unittest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make init
    - name: Running test
      run: |
        make test
    - name: Badge creation
      run: |
        coverage-badge -o coverage.svg
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage.svg
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
